/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import acciones.DepartamentoAcciones;
import clases.DepartamentoClass;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author aurrera
 */
public class CrearDepartamento extends javax.swing.JFrame {
    
    static void mostrar(){
        CrearDepartamento crearDepartamento = new CrearDepartamento();
        crearDepartamento.cargarWidget();
        crearDepartamento.setSize(700, 400);
        crearDepartamento.setVisible(true);
        crearDepartamento.requestFocus();
        
    }
    DepartamentoNuevo departamentoNuevo;
    /**
     * Creates new form CrearDepartamento
     */
    private CrearDepartamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancelarButton = new javax.swing.JButton();
        guardarButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        departamentoPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crear Departamento");

        cancelarButton.setBackground(new java.awt.Color(255, 153, 153));
        cancelarButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        guardarButton.setBackground(new java.awt.Color(204, 255, 204));
        guardarButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        guardarButton.setText("Guardar");
        guardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarButtonActionPerformed(evt);
            }
        });

        departamentoPanel.setBackground(new java.awt.Color(255, 255, 255));
        departamentoPanel.setToolTipText("");
        departamentoPanel.setLayout(new javax.swing.BoxLayout(departamentoPanel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(departamentoPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(cancelarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                .addComponent(guardarButton)
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarButton)
                    .addComponent(guardarButton))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void guardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButtonActionPerformed
    DepartamentoClass departamentoClass = departamentoNuevo.getDepartamentoClass();

        try {
            DepartamentoAcciones.guardarDepartamento(departamentoClass);
            directorio.Directorio.principal.agregarDepartamento(departamentoClass);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(CrearDepartamento.class.getName()).log(Level.SEVERE, null, ex);
        }
     
    
                
    }//GEN-LAST:event_guardarButtonActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarButton;
    private javax.swing.JPanel departamentoPanel;
    private javax.swing.JButton guardarButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void cargarWidget() {
        departamentoNuevo = new DepartamentoNuevo();
        departamentoNuevo.setVisible(true);
        departamentoPanel.removeAll();
        departamentoPanel.add(departamentoNuevo);
        validate();
    }
}
