/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import acciones.DepartamentoAcciones;
import clases.DepartamentoClass;
import clases.PersonaClass;
import static directorio.Directorio.principal;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import gui.*;

/**
 *
 * @author aurrera
 */
public class Principal extends javax.swing.JFrame {
     static  void mostrarlos(){
       Principal Principal = new Principal();
     //   crearPersonas.cargarWidget();
       principal.setVisible(true);
        principal.requestFocus();
            }


    ArrayList <DepartamentoVisualizar> departamentosList = new ArrayList<>(); 
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloPanel = new javax.swing.JPanel();
        tituloLabel = new javax.swing.JLabel();
        departamentosButton = new javax.swing.JButton();
        agregarButton = new javax.swing.JButton();
        personalButton = new javax.swing.JButton();
        actividadesLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        departamentosPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Departamentos");
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tituloPanel.setBackground(new java.awt.Color(255, 255, 255));

        tituloLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(0, 51, 153));
        tituloLabel.setText("Directorio Organizacional");

        javax.swing.GroupLayout tituloPanelLayout = new javax.swing.GroupLayout(tituloPanel);
        tituloPanel.setLayout(tituloPanelLayout);
        tituloPanelLayout.setHorizontalGroup(
            tituloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(tituloLabel)
                .addContainerGap(223, Short.MAX_VALUE))
        );
        tituloPanelLayout.setVerticalGroup(
            tituloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tituloPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tituloLabel)
                .addGap(21, 21, 21))
        );

        departamentosButton.setBackground(new java.awt.Color(0, 0, 153));
        departamentosButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        departamentosButton.setForeground(new java.awt.Color(255, 255, 255));
        departamentosButton.setText("Departamentos");

        agregarButton.setBackground(new java.awt.Color(204, 204, 255));
        agregarButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        agregarButton.setText("Agregar");
        agregarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarButtonActionPerformed(evt);
            }
        });

        personalButton.setBackground(new java.awt.Color(204, 204, 255));
        personalButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        personalButton.setText("Personal");
        personalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personalButtonActionPerformed(evt);
            }
        });

        actividadesLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        actividadesLabel.setForeground(new java.awt.Color(0, 0, 102));
        actividadesLabel.setText("Actividades");

        departamentosPanel.setBackground(new java.awt.Color(255, 255, 255));
        departamentosPanel.setLayout(new javax.swing.BoxLayout(departamentosPanel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane2.setViewportView(departamentosPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tituloPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(departamentosButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(actividadesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(agregarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(personalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(departamentosButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(actividadesLabel)
                        .addGap(32, 32, 32)
                        .addComponent(agregarButton)
                        .addGap(34, 34, 34)
                        .addComponent(personalButton)
                        .addGap(0, 246, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarButtonActionPerformed
        CrearDepartamento.mostrar();
    }//GEN-LAST:event_agregarButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        cargarDepartamentos();
    }//GEN-LAST:event_formWindowOpened

    private void personalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalButtonActionPerformed
         Personas personas;
         personas = new Personas();
         personas.setVisible(true);
         personas.requestFocus();
        
        Personas.mostrarlos();

    }//GEN-LAST:event_personalButtonActionPerformed

       
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actividadesLabel;
    private javax.swing.JButton agregarButton;
    private javax.swing.JButton departamentosButton;
    private javax.swing.JPanel departamentosPanel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton personalButton;
    private javax.swing.JLabel tituloLabel;
    private javax.swing.JPanel tituloPanel;
    // End of variables declaration//GEN-END:variables

    void agregarDepartamento(DepartamentoClass departamentoClass) {
        
        DepartamentoVisualizar departamentoVisualizar = new DepartamentoVisualizar(departamentoClass);
        departamentosList.add(departamentoVisualizar);
        departamentosPanel.add(departamentoVisualizar);
        validate();
        requestFocus();
        
    }

    private void cargarDepartamentos() {
        try {
            ArrayList<DepartamentoClass> departamentos =  DepartamentoAcciones.obtenerDepartamentos();
            departamentosList.clear();
            departamentosPanel.removeAll();
            for(DepartamentoClass departamento : departamentos){
                DepartamentoVisualizar departamentoVisualizar = new DepartamentoVisualizar(departamento);
                departamentosList.add(departamentoVisualizar);
                departamentosPanel.add(departamentoVisualizar);
            }
            validate();
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void eliminarDepartamento(DepartamentoVisualizar departamento) {
        departamentosList.remove(departamento);
        departamentosPanel.remove(departamento);
        validate();
    }

    void editarDepartamento(DepartamentoVisualizar departamento) {
    }

    




    
}
